create table
  public."reports" (
    id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    created_by uuid not null,
    constraint wdireports_pkey primary key (id),
    constraint report_created_by_fkey foreign key (created_by) references employees (id)
  ) tablespace pg_default;

